baseURL = 'https://roennie123.github.io/sketchingWithHardware/'
languageCode = 'en-us'
title = 'Roennie123 Blog'
theme = "ananke"

resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  background_color_class = "bg-silver"
  recent_posts_number = 3
  body_classes = "helvetica bg-moon-gray"
  post_content_classes = "helvetica bg-moon-gray"

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/Roennie123"